### ISSUE TITLE
[求助]天池文娱的数据集能分享一下吗

### ISSUE THREAD

**Issue by Ying-Kang** [IvanaXu/PyTools#1]
您好，我在天池上看见您分享的拉取数据集的代码
那时候我还没有学习视频事件识别，
现在想学习一下，不知道能不能方便分享一个比赛数据集的百度云呢？

**Comment by IvanaXu** [comment]
check your e-mail

**Comment by Ying-Kang** [comment]
> check your e-mail

1312976591@qq.com
thanks for sharing

**Comment by Ying-Kang** [comment]
sorry sir or madam
I have not received the dataset,
could you please send me again?
my email address: 1312976591@qq.com
best wishes

**Comment by IvanaXu** [comment]
I send **proj.zip**(the download code、readme、json、example) to your e-mail
Or get it by [https://ivan-bucket-out-001.oss-cn-beijing.aliyuncs.com/out/proj.zip](url)
_You can download by yourself. THX_
